export { default as Home } from "./Home";
export { default as Productos } from "./Productos";
export { default as DetallesProductos } from "./DetallesProductos";
export { default as Carrito } from "./carrito";
export { default as Blogs } from "./blogs";
export { default as DetalleBlog } from "./DetalleBlog";
export { default as Contacto } from "./Contacto";
export { default as Ofertas } from "./Ofertas";
export { default as Nosotros } from "./Nosotros";